#pragma once

#include "Louron.h"

#include <fstream>


#if defined(L_PLATFORM_WINDOWS)
#include "clang-c/Index.h"
#endif

#if defined(L_PLATFORM_WINDOWS)
#define CLANG_EXECUTABLE "Resources\\Compiler\\windows\\clang++.exe"
#define SHARED_FLAG "-shared"
#define PIC_FLAG "" // MSVC doesn't need -fPIC
#elif defined(L_PLATFORM_LINUX)
#define CLANG_EXECUTABLE "./Resources/Compiler/linux/clang++"
#define SHARED_FLAG "-shared"
#define PIC_FLAG "-fPIC"
#endif

namespace Utils 
{

	class ScriptReflectionGenerator 
	{

	public:

		ScriptReflectionGenerator(const std::filesystem::path& scriptsDir, const std::filesystem::path& outputFile, const std::filesystem::path& includeDir)
			: m_ScriptsDir(scriptsDir), m_OutputFile(outputFile), m_IncludeDir(includeDir) {
		}

		void Generate(const std::filesystem::path& absolute_file_path_engine_api);

	private:

		struct FieldInfo {
			std::string name;
			std::string type;
		};

		struct ScriptClassInfo {
			std::string name;
			std::vector<FieldInfo> exposed_fields;
			std::filesystem::path file_path;
		};

		const std::filesystem::path& m_ScriptsDir;
		const std::filesystem::path& m_OutputFile;
		const std::filesystem::path& m_IncludeDir;
		std::vector<ScriptClassInfo> m_ParsedScripts;
		bool m_InheritsFromIScript = false;

		std::filesystem::path current_header_file_path = {};

		#if defined(L_PLATFORM_WINDOWS)

		bool HasExposedAttribute(CXCursor cursor);

		static CXChildVisitResult ClassVisitor(CXCursor cursor, CXCursor parent, CXClientData clientData);

		static CXChildVisitResult TUVisitor(CXCursor cursor, CXCursor parent, CXClientData clientData);

		void ParseHeader(const std::filesystem::path& path, const std::filesystem::path& absolute_file_path_engine_api);

		#endif

		void WriteReflectionFile();

		std::string ToFieldTypeEnum(const std::string& typeStr);

		ScriptClassInfo* m_CurrentClass = nullptr;
	};

	static bool BuildScriptCodeAssembly(const std::filesystem::path& scripts_directory, bool overwrite_current_assembly = true)
	{
		std::filesystem::path generated_file_path = scripts_directory / "Generated/AutoGenerated_Reflection.cpp";
		std::filesystem::path script_core_api_include_path = scripts_directory / "Script Core API";
		const std::filesystem::path& output_dll_path = scripts_directory / (overwrite_current_assembly ? "Binaries/ScriptCode.dll" : "Binaries/ScriptCode.dll.tmp");

		// -------------------------
		//    Copy Script API
		// -------------------------
		if (std::filesystem::exists("Resources/Script Core API"))
		{
			if (std::filesystem::exists(script_core_api_include_path))
			{
				try
				{
					std::filesystem::remove_all(script_core_api_include_path);
				}
				catch (const std::filesystem::filesystem_error& e)
				{
					L_APP_ERROR("Could Not Remove Old Script Core API Include Directory: {}", e.what());
					L_APP_ERROR("Could Not Compile New Script Code DLL. Try 'File -> Reloading Script Assembly' manually.");
					return false;
				}
			}

			std::filesystem::copy(
				"Resources/Script Core API",
				script_core_api_include_path,
				std::filesystem::copy_options::recursive
			);
		}

		// -------------------------
		//    Generate Reflection
		// -------------------------
		{
			L_PROFILE_SCOPE("Script Reflection Generation");
			L_APP_INFO("Generating Script Reflection File: {}", generated_file_path.string());

			ScriptReflectionGenerator generator(scripts_directory, generated_file_path, script_core_api_include_path);
			generator.Generate(std::filesystem::absolute(script_core_api_include_path).string());
		}

		L_APP_INFO("Script Reflection Generation Complete. Time Taken: {:.2f} seconds", Louron::Profiler::Get().GetResults()["Script Reflection Generation"].Time / 1000.0f);

		// -------------------------
		//    Build Script DLL
		// -------------------------
		{
			L_APP_INFO("Building Script DLL: {}", output_dll_path.string());

			std::ostringstream compileCommand;
			compileCommand << CLANG_EXECUTABLE
				<< " -std=c++20 "
				<< SHARED_FLAG << ' '
				<< PIC_FLAG << ' '
				<< "-I \"" << script_core_api_include_path.string() << "\" "
				<< "-I \"" << scripts_directory.string() << "\" "
				<< "-o \"" << output_dll_path.string() << "\" "
				<< '"' << generated_file_path.string() << "\"";

			// Append all .cpp files from script directory (excluding auto-gen)
			for (const auto& entry : std::filesystem::recursive_directory_iterator(scripts_directory)) {
				if (entry.path().extension() == ".cpp" && entry.path().filename() != "AutoGenerated_Reflection.cpp") {
					compileCommand << " -Wno-everything \"" << entry.path().string() << "\"";
				}
			}

			// Step 3: Move Current DLL to Safe Keeping
			if (overwrite_current_assembly && std::filesystem::exists(output_dll_path))
			{
				try
				{
					std::filesystem::rename(output_dll_path, output_dll_path.string() + ".tmp");
				}
				catch (const std::filesystem::filesystem_error& e)
				{
					L_APP_ERROR("Could Not Append Old Script DLL Extension to .tmp: {}", e.what());
				}
			}

			// Step 4: Execute compile command
			L_APP_INFO("Executing Compile Command: {}", compileCommand.str());
			int result = std::system(compileCommand.str().c_str());
			if (result != 0) 
			{
				if (overwrite_current_assembly && std::filesystem::exists(output_dll_path.string() + ".tmp"))
				{
					try
					{
						std::filesystem::rename(output_dll_path.string() + ".tmp", output_dll_path);
					}
					catch (const std::filesystem::filesystem_error& e)
					{
						L_APP_ERROR("Could Not Rename Old Script DLL Extension to .dll: {}", e.what());
					}
				}

				L_APP_ERROR("Script DLL Compilation Failed With Code: {}", std::to_string(result));
				return false;
			}

			if (overwrite_current_assembly && std::filesystem::exists(output_dll_path.string() + ".tmp"))
			{
				try
				{
					std::filesystem::remove(output_dll_path.string() + ".tmp");
				}
				catch (const std::filesystem::filesystem_error& e)
				{
					L_APP_ERROR("Could Not Remove Old Script DLL: {}", e.what());
				}
			}

			L_APP_INFO("Script Compilation Successful. Output DLL: {}", output_dll_path.string());
		}

		return true;
	}

	static std::string GenerateScriptFile(const std::filesystem::path& file_path)
	{
		std::string script_name = file_path.stem().string();

		script_name.erase(std::remove(script_name.begin(), script_name.end(), ' '), script_name.end());

		// Load template file
		std::ifstream template_file("Resources/Templates/Template C++ Script.h");
		if (!template_file.is_open()) {
			L_APP_ERROR("Failed to open script template file.");
			return "";
		}

		std::stringstream buffer;
		buffer << template_file.rdbuf();
		std::string content = buffer.str();
		template_file.close();

		// Replace placeholders
		size_t pos;
		while ((pos = content.find("<<SCRIPT_NAME>>")) != std::string::npos) 
		{
			content.replace(pos, 15, script_name);
		}

		// C# Script File 
		std::ofstream script_file_path(file_path);

		if (!script_file_path.is_open()) {
			L_APP_ERROR("Failed to Generate C++ Script Header File: {}", file_path.string());
			return "";
		}

		// Write the content to the file
		script_file_path << content;

		script_file_path.close();

		return script_name;
	}

	static std::string OnCreateNewScriptGUI(bool* script_create) {
		std::string script_full_name;

		if (*script_create){
			ImGui::OpenPopup("Create New Script");

			// Calculate window size: 25% of the screen width, minimum 300.0f
			float windowWidth = glm::max(300.0f, ImGui::GetContentRegionAvail().x * 0.25f);
			float windowHeight = 100.0f; // Fixed height
			ImVec2 windowSize(windowWidth, windowHeight);
			ImGui::SetNextWindowSize(windowSize);

			ImGuiViewport* viewport = ImGui::GetMainViewport();
			ImVec2 viewportPos = viewport->Pos;
			ImVec2 viewportSize = viewport->Size;

			// Calculate centered position
			ImVec2 windowPos(
				viewportPos.x + (viewportSize.x - windowWidth) * 0.5f, // Center horizontally
				viewportPos.y + (viewportSize.y - windowHeight) * 0.5f // Center vertically
			);
			ImGui::SetNextWindowPos(windowPos);
		}


		static std::filesystem::path new_script_path{};
		static bool show_warning_popup = false;
		if (ImGui::BeginPopupModal("Create New Script", NULL, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_AlwaysAutoResize)) {

			// Grey out the background
			ImGui::Text("Create a New Script");

			// Input fields

			float first_coloumn_width = ImGui::CalcTextSize("Script Name").x + 10.0f;

			ImGui::Columns(2, "New_Script_Cols", false);
			ImGui::SetColumnWidth(-1, first_coloumn_width);

			ImGui::Text("Script Name");

			ImGui::NextColumn();

			char buf[256];

		#if defined(L_PLATFORM_WINDOWS)
			strncpy_s(buf, new_script_path.string().c_str(), sizeof(buf));
		#else
			strncpy(buf, new_script_path.string().c_str(), sizeof(buf));
		#endif
		
			ImGui::InputText("##Folder Path", buf, sizeof(buf));
			new_script_path = buf;

			ImGui::SameLine();

			if (ImGui::Button("...")) 
			{
				new_script_path = Louron::Utils::SaveFile("C++ Script (*.h)\0*.h\0", (Louron::Project::GetActiveProject()->GetProjectDirectory() / "Scripts")); // Open File Dialog in Scripts Folder

				if (new_script_path.lexically_normal().string().find((Louron::Project::GetActiveProject()->GetProjectDirectory() / "Scripts").lexically_normal().string()) != 0) {
					new_script_path = "";
					show_warning_popup = true; // Trigger warning popup
					*script_create = false;
				}
				else {
					new_script_path = new_script_path.filename();
				}
			}

			ImGui::Columns(1);

			// Buttons for Create and Cancel
			if (ImGui::Button("Create") || Louron::Engine::Get().GetInput().GetKeyDown(GLFW_KEY_ENTER)) 
			{
				if (new_script_path.extension() != ".h")
					new_script_path.replace_extension(".h");

				new_script_path = std::filesystem::absolute(Louron::Project::GetActiveProject()->GetProjectDirectory() / "Scripts" / new_script_path);

				//check if in script directory
				if (new_script_path.lexically_normal().string().find((Louron::Project::GetActiveProject()->GetProjectDirectory() / "Scripts").lexically_normal().string()) != 0) {
					new_script_path = "";
					show_warning_popup = true; // Trigger warning popup
					*script_create = false;
				}
				else {

					script_full_name = ::Utils::GenerateScriptFile(new_script_path);

					std::string command = "start \"\" \"" + new_script_path.string() + "\"";
					std::system(command.c_str());

					// Add temporary class to the entity classes list, this is so that it shows in the editor.
					// NOTE: We don't actually need to initialise a ScriptClass for this yet. The AppAssembly 
					// will reload regardless when we're scripting, and it will add it anyway! This is more for
					// user experience when creating a script.
					Louron::ScriptManager::Get()->AddDummyScriptClass(script_full_name);

					new_script_path = "";
					*script_create = false; // Close the dialog
					ImGui::CloseCurrentPopup();
				}
			}

			ImGui::SameLine();

			if (ImGui::Button("Cancel")) {
				*script_create = false; // Close the dialog
				ImGui::CloseCurrentPopup();
			}

			ImGui::EndPopup();
		}

		// Warning popup
		if (show_warning_popup) {
			ImGui::OpenPopup("ScriptWarningPopup");

			// Calculate window size: 25% of the screen width, minimum 300.0f
			float windowWidth = glm::max(300.0f, ImGui::GetContentRegionAvail().x * 0.25f);
			float windowHeight = 100.0f; // Fixed height
			ImVec2 windowSize(windowWidth, windowHeight);
			ImGui::SetNextWindowSize(windowSize);

			ImGuiViewport* viewport = ImGui::GetMainViewport();
			ImVec2 viewportPos = viewport->Pos;
			ImVec2 viewportSize = viewport->Size;

			// Calculate centered position
			ImVec2 windowPos(
				viewportPos.x + (viewportSize.x - windowWidth) * 0.5f, // Center horizontally
				viewportPos.y + (viewportSize.y - windowHeight) * 0.5f // Center vertically
			);
			ImGui::SetNextWindowPos(windowPos);
		}

		if (ImGui::BeginPopupModal("ScriptWarningPopup", NULL, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_AlwaysAutoResize)) {
			ImGui::TextWrapped("The selected file path is not within the Scripts directory. Please choose a valid path within the Scripts directory.");

			if (ImGui::Button("OK")) 
			{
				show_warning_popup = false; // Close the warning popup
				*script_create = true;
				ImGui::CloseCurrentPopup();
			}

			ImGui::EndPopup();
		}

		return script_full_name;
	}

}